---
title: "previous_positions"
author: "Sima Biondi"
date: "9/13/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(warn = -1)
library(ggplot2)
library(dplyr)
library(tidyr)
library(finalfit)
library(readxl)
library(forcats)
library(stringr)
fig.path = here::here("figs")

```

# Read data
```{r}
df = read.csv("data/Old versions of data/Part_2_v1.csv")

```

## Create datasets of previous positions: remove unnecessary vars, split into 2 separate dfs 
```{r}
df_alt_pre76_prev = data.frame(Type_of_prev_position = "Alternate", n = 4)
df_pre76_previous = df %>%
  select(Year_started, Type_of_prev_position, Type_of_following_position) %>%
  filter(Year_started < 1976) %>%
  count(Type_of_prev_position) %>%
  filter(n >3 | Type_of_prev_position == "Academia") %>%
  bind_rows(df_alt_pre76_prev) %>%
  mutate(percent = n/sum(n), time_period = "pre_76")

df_alt_post75_prev = data.frame(Type_of_prev_position = "Alternate", n = 2)
df_post75_prev = df %>%
  select(Year_started, Type_of_prev_position, Type_of_following_position) %>%
  filter(Year_started > 1975) %>%
  count(Type_of_prev_position) %>%
  filter(n > 2 | Type_of_prev_position == "Private practice") %>%
  bind_rows(df_alt_post75_prev) %>%
  mutate(percent = n/sum(n), time_period = "post_75")

prev_position_df = rbind(df_pre76_previous, df_post75_prev)
prev_position_df$time_period = factor(prev_position_df$time_period,
                                      levels = c("pre_76", "post_75"))


```


## Create datasets of future positions: remove unnecessary vars, split into 2 separate dfs 
```{r}
df_alt_pre76_future = data.frame(Type_of_following_position = "Alternate", n = 22)
df_pre76_future = df %>%
  select(Year_started, Type_of_prev_position, Type_of_following_position) %>%
  filter(Year_started < 1976) %>%
  count(Type_of_following_position) %>%
  filter(Type_of_following_position == "Academia" | Type_of_following_position == "Government" | Type_of_following_position == "Industry" | Type_of_following_position == "Law firm" | Type_of_following_position == "Private practice") %>%
  bind_rows(df_alt_pre76_future) %>%
  mutate(percent = n/sum(n), time_period = "pre_76")

df_alt_post75_future = data.frame(Type_of_following_position = c("Private practice", "Alternate"), n = c(0,9))
df_post75_future = df %>%
  select(Year_started, Type_of_prev_position, Type_of_following_position) %>%
  filter(Year_started > 1975) %>%
  count(Type_of_following_position) %>%
  filter(Type_of_following_position == "Academia" | Type_of_following_position == "Government" | Type_of_following_position == "Industry" | Type_of_following_position == "Law firm") %>%
  bind_rows(df_alt_post75_future) %>%
  mutate(percent = n/sum(n), time_period = "post_75")

future_position_df = rbind(df_pre76_future, df_post75_future)
future_position_df$time_period = factor(future_position_df$time_period,
                                      levels = c("pre_76", "post_75"))

```


## Summarizing revolving door
```{r}

df_summary = df %>%
  mutate(era = case_when(Year_started < 1976 ~ "Pre-1976",
                         T ~ "Post-1975")) %>%
  select(Type_of_prev_position, Type_of_following_position, era) %>%
  
  mutate(sum_type_prev_pos = case_when(Type_of_prev_position == "Industry" | 
                                         Type_of_prev_position == "Law firm" ~ "Law firm/\nindustry",
                                       Type_of_prev_position == "Government" | 
                                         Type_of_prev_position == "Alternate" |
                                         Type_of_prev_position == "Academia" ~ "Government/\nacademia",
                                       T ~ "Other")) %>%
  mutate(sum_type_follow_pos = case_when(Type_of_following_position == "Industry" | 
                                           Type_of_following_position == "Law firm" ~ "Law firm/\nindustry",
                                         Type_of_following_position == "Government" | 
                                           Type_of_following_position == "Alternate" |
                                           Type_of_following_position == "Academia" ~ "Government/\nacademia",
                                         T ~ "Other")) %>%
  pivot_longer(cols = !era, values_to = "Type of positions") %>%
  filter(name != "Type_of_prev_position" & name != "Type_of_following_position") %>%
  mutate(direction = case_when(str_detect(name, "prev") ~ "Previous position",
                               T ~ "Following position")) %>%
  
  group_by(era, name, `Type of positions`, direction) %>%
  summarise(count = n()) %>%
  ungroup() %>%
  group_by(era, direction) %>%
  mutate(freq = (count/sum(count))* 100) %>%
  mutate(direction_f = factor(direction, levels = c('Previous position', 'Following position')),
         Era = factor(era, levels = c('Pre-1976', 'Post-1975'))) 
  df_summary

```




## Create graphs
```{r}

#cbbPalette = c("#000000", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

p_previous_positions = prev_position_df %>%
  mutate(`Time period` = recode(time_period, 
                                'pre_76' = 'Pre-1976',
                                'post_75' = 'Post-1975')) %>%
ggplot(aes(x =Type_of_prev_position, y= percent, fill = `Time period`)) + geom_bar(stat="identity", position=position_dodge2(reverse = FALSE)) +
  xlab("Type of position") + ylab("% of officials employed") +   
  ggtitle("Composition of primary position before joining") + 
  scale_fill_hue(name="Time period", labels= c("Pre-1976", "Post-1975")) +
  theme_minimal() + scale_fill_grey()


p_future_positions = future_position_df %>%
    mutate(`Time period` = recode(time_period, 
                                'pre_76' = 'Pre-1976',
                                'post_75' = 'Post-1975')) %>%
  ggplot(aes(x = Type_of_following_position, y= percent, fill = `Time period`)) + geom_bar(stat="identity", position=position_dodge2()) +
  xlab("Type of position") + ylab("% of officials employed") +   
  ggtitle("Composition of primary position after leaving") + 
  scale_fill_discrete(name="Time period", labels= c("Pre-1976", "Post-1975")) +
  theme_minimal()   +scale_fill_grey()


p_summary_graph = df_summary %>%
  ggplot(aes(x = `Type of positions`, y = freq, fill = Era)) + 
    geom_bar(stat = "identity", position = position_dodge2()) +
  facet_wrap(vars(direction_f)) +
  labs(title = "Composition of officials' career trajectories", y = "% of officials employed") +
  theme_bw() + scale_fill_grey()




```

```{r}

p_previous_positions
ggsave(path = fig.path, "previous_position_fig.png")

p_future_positions
ggsave(path = fig.path, "future_position_fig.png")

p_summary_graph
ggsave(path = fig.path, "summary_position_fig.png")

```

```{r}
df_summary %>%
  filter(direction == "Previous position")

prev_position_df %>%
  mutate(adding = case_when(Type_of_prev_position == "Academia" ~ 1,
                            Type_of_prev_position == "Government" ~ 1,
                            Type_of_prev_position == "Law firm" ~ 2,
                            Type_of_prev_position == "Industry" ~ 2,
                            T ~ 3)) %>%
  group_by(time_period, adding) %>%
  summarise(n = sum(n), Type_of_prev_position = first(Type_of_prev_position), percent = mean(percent)) %>%
  select(-adding)
```

```{r party affiliation}

df_party_affil = read_excel("data/Part_2_ftc_bios_presidents.xlsx")
df_party_affil %>%
  mutate(partyMatchBool = case_when(presidentParty == partyAffiliation ~ "match",
                                 T ~ "no match")) %>%
  mutate(partyMatchString = case_when(presidentParty == "D" & partyAffiliation == "D" ~ "D",
                                      presidentParty == "D" & partyAffiliation == "Progressive" ~ "D",
                                      presidentParty == "R" & partyAffiliation == "R" ~ "R",
                                      presidentParty == "D" & partyAffiliation == "R" ~ "Dem-leaning Rep",
                                      presidentParty == "R" & partyAffiliation == "D" ~ "Rep-leaning Dem",
                                      partyAffiliation == "NA" ~ "No individual affiliation",
                                      partyAffiliation == "Independent" ~ "Independent",

                                 T ~ "no match")) %>%
  group_by(partyMatchString) %>%
  count()


df_party_affil %>%
 # filter(presidentParty == "acting") %>%
  ggplot(aes(x = Year_started, fill = presidentParty)) + geom_dotplot(binwidth=4, method='histodot')    


df_party_affil %>%
 # filter(presidentParty == "acting") %>%
  ggplot(aes(x = Year_started, fill = presidentParty)) + geom_dotplot(method='histodot', binwidth = 1)    


df_party_affil %>%
  ggplot(aes(x = Year_started, fill = presidentParty)) + 
    geom_histogram(binwidth = 8, position = "dodge") + 
  theme_classic() +
  scale_fill_manual(values = c("acting" = "green",
                               "D" = "blue",
                               "R" = "red")) +
  labs(x = "Year", y = "Count of officials", fill = "Party of nominating president",
       title = "Party of nominating president for antitrust AAGs and FTC Commissioners")
 
df_party_affil %>%
  filter(presidentParty == "acting") 

```

